apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-cert
  namespace: default
spec:
  secretName: local-tls
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days
  commonName: sunshiiiiine.com
  dnsNames:
    - sunshiiiiine.com
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
